import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Peak test Dani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen w-full bg-gray-50 text-gray-900">
        <header className="w-full bg-white shadow-md p-4">
          <div className="container mx-auto flex items-center justify-between">
            <h1 className="text-xl font-semibold">My App</h1>
          </div>
        </header>
        <main className="flex-grow container mx-auto p-4">{children}</main>
        <footer className="w-full bg-gray-100 p-4 text-center text-sm text-gray-600">
          {new Date().getFullYear()}
        </footer>
      </body>
    </html>
  );
}